(function(){
  const d=window.SITE_DATA;
  const mount=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html};
  mount('positions-list',d.positions.map((x,i)=>`<li class="flex gap-3"><span class="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-gold-400/15 text-xs font-bold text-gold-500">${i+1}</span><span>${x}</span></li>`).join(''));
  mount('timeline-list',d.timeline.map((x,i)=>`<article class="reveal relative pl-10"><span class="absolute left-0 top-2 h-4 w-4 rounded-full border-4 border-ivory bg-gold-400 ring-1 ring-gold-400 dark:border-slate-950"></span><button data-accordion class="card w-full text-left" aria-expanded="${i===0}" aria-controls="timeline-${i}"><span class="flex items-start justify-between gap-5"><span><span class="text-xs font-bold uppercase tracking-[.15em] text-gold-500">${x.period} · ${x.type}</span><strong class="mt-2 block font-display text-2xl text-navy-900 dark:text-white">${x.role}</strong><span class="mt-1 block text-sm text-slate-500 dark:text-slate-400">${x.org}</span></span><span data-plus class="text-2xl text-gold-500">${i===0?'−':'+'}</span></span><span id="timeline-${i}" class="mt-4 block border-t border-slate-100 pt-4 text-sm leading-6 text-slate-600 dark:border-slate-800 dark:text-slate-300" ${i===0?'':'hidden'}>${x.detail}</span></button></article>`).join(''));
  mount('projects-grid',d.projects.map((x,i)=>`<article class="card reveal flex flex-col"><div class="flex items-center justify-between"><span class="grid h-12 w-12 place-items-center rounded-xl bg-navy-900 text-sm font-bold text-gold-300">${x.icon}</span><span class="text-[10px] font-bold uppercase tracking-[.15em] text-slate-400">${x.tag}</span></div><h2 class="mt-6 text-3xl font-semibold text-navy-900 dark:text-white">${x.title}</h2><p class="mt-3 leading-6 text-slate-600 dark:text-slate-300">${x.summary}</p><button data-accordion class="mt-auto pt-6 text-left text-sm font-bold text-gold-500" aria-expanded="false" aria-controls="project-${i}">Read more <span data-plus>+</span></button><p id="project-${i}" class="mt-3 border-t border-slate-100 pt-4 text-sm leading-6 text-slate-600 dark:border-slate-800 dark:text-slate-300" hidden>${x.detail}</p></article>`).join(''));
  mount('awards-track',d.awards.map(x=>`<article class="card min-w-[82vw] snap-start sm:min-w-[380px]"><span class="text-sm font-bold text-gold-500">${x.year}</span><h2 class="mt-3 text-3xl font-semibold text-navy-900 dark:text-white">${x.title}</h2><p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">${x.body}</p></article>`).join(''));
  mount('awards-grid',d.awards.map(x=>`<article class="card reveal"><span class="text-sm font-bold text-gold-500">${x.year}</span><h3 class="mt-2 text-2xl font-semibold text-navy-900 dark:text-white">${x.title}</h3><p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">${x.body}</p></article>`).join(''));
  mount('publications-list',d.publications.map((x,i)=>`<a href="${x.url}" target="_blank" rel="noopener noreferrer" class="group grid gap-5 border-b border-slate-200 py-8 md:grid-cols-[140px_1fr_auto] md:items-center dark:border-slate-700"><span class="text-sm font-bold text-gold-500">${x.date}</span><span><span class="text-xs font-bold uppercase tracking-[.15em] text-slate-400">${x.publication}</span><strong class="mt-2 block font-display text-2xl leading-tight text-navy-900 group-hover:text-gold-500 dark:text-white">${x.title}</strong></span><span class="text-xl text-gold-500" aria-hidden="true">↗</span><span class="sr-only">Opens in new tab</span></a>`).join(''));
  mount('recognition-grid',d.recognition.map(x=>`<article class="border-l-2 border-gold-400 pl-5"><h3 class="text-2xl font-semibold text-navy-900 dark:text-white">${x.title}</h3><p class="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">${x.text}</p></article>`).join(''));
  mount('extras-list',d.extras.map(x=>`<li class="rounded-xl bg-white p-4 text-sm shadow-sm dark:bg-slate-900">${x}</li>`).join(''));
})();
